import { Option } from '../components/ui/multiple-selector'

export const TOPICS: Option[] = [
  { label: 'CEO', value: 'CEO', group: 'Topics' },
  { label: 'CFO', value: 'CFO', group: 'Topics' },
  { label: 'COO', value: 'COO', group: 'Topics' },
  { label: 'Call Transcript', value: 'callscript', group: 'Topics' },
  { label: 'Class action lawsuit', value: 'Class+Action+Lawsuit', group: 'Topics' },
  { label: 'Conference', value: 'conference', group: 'Topics' },
  { label: 'Press release', value: 'pressrelease', group: 'Topics' },
  { label: 'Shareholder alert', value: 'Shareholder+Alert', group: 'Topics' },
  { label: 'Cannabis', value: 'cannabis', group: 'Topics' },
  { label: 'Cramer', value: 'cramer', group: 'Topics' },
  { label: 'Dividend', value: 'dividend', group: 'Topics' },
  { label: 'Earnings', value: 'earnings', group: 'Topics' },
  { label: 'Gold', value: 'gold', group: 'Topics' },
  { label: 'Layoffs', value: 'Layoffs', group: 'Topics' },
  { label: 'Mad Money', value: 'madmoney', group: 'Topics' },
  { label: 'Mergers & acquisitions', value: 'manda', group: 'Topics' },
  { label: 'Oil', value: 'oil', group: 'Topics' },
  { label: 'Paywall', value: 'paywall', group: 'Topics' },
  { label: 'Paywall (limit)', value: 'paylimitwall', group: 'Topics' },
  { label: 'Podcast', value: 'podcast', group: 'Topics' },
  { label: 'Political', value: 'political', group: 'Topics' },
  { label: 'Product', value: 'product', group: 'Topics' },
  { label: 'Real estate', value: 'Real+Estate', group: 'Topics' },
  { label: 'Recession', value: 'Recession', group: 'Topics' },
  { label: 'SPAC', value: 'SPAC', group: 'Topics' },
  { label: 'Technical analysis', value: 'tanalysis', group: 'Topics' },
  { label: 'Warren Buffett', value: 'wbuffett', group: 'Topics' },
]

export const SECTORS: Option[] = [
  { label: 'All Sectors', value: 'all', group: 'Sectors' },
  { label: 'Basic Materials', value: 'Basic+Materials', group: 'Sectors' },
  { label: 'Conglomerates', value: 'Conglomerates', group: 'Sectors' },
  { label: 'Financial', value: 'Financial', group: 'Sectors' },
  { label: 'Healthcare', value: 'Healthcare', group: 'Sectors' },
  { label: 'Industrial Goods', value: 'Industrial+Goods', group: 'Sectors' },
  { label: 'Services', value: 'Services', group: 'Sectors' },
  { label: 'Technology', value: 'Technology', group: 'Sectors' },
  { label: 'Utilities', value: 'Utilities', group: 'Sectors' },
]
