import { Option } from '../components/ui/multiple-selector'

export const TOPICS: Option[] = [
  { label: 'CEO', value: 'CEO', group: 'Topics' },
  { label: 'CFO', value: 'CFO', group: 'Topics' },
  { label: 'COO', value: 'COO', group: 'Topics' },
  { label: 'Call Transcript', value: 'callscript', group: 'Topics' },
  { label: 'Class action lawsuit', value: 'Class+Action+Lawsuit', group: 'Topics' },
  { label: 'Conference', value: 'conference', group: 'Topics' },
  { label: 'Press release', value: 'pressrelease', group: 'Topics' },
  { label: 'Shareholder alert', value: 'Shareholder+Alert', group: 'Topics' },
  { label: 'Cannabis', value: 'cannabis', group: 'Topics' },
  { label: 'Cramer', value: 'cramer', group: 'Topics' },
  { label: 'Dividend', value: 'dividend', group: 'Topics' },
  { label: 'Earnings', value: 'earnings', group: 'Topics' },
  { label: 'Gold', value: 'gold', group: 'Topics' },
  { label: 'Layoffs', value: 'Layoffs', group: 'Topics' },
  { label: 'Mad Money', value: 'madmoney', group: 'Topics' },
  { label: 'Mergers & acquisitions', value: 'manda', group: 'Topics' },
  { label: 'Oil', value: 'oil', group: 'Topics' },
  { label: 'Paywall', value: 'paywall', group: 'Topics' },
  { label: 'Paywall (limit)', value: 'paylimitwall', group: 'Topics' },
  { label: 'Podcast', value: 'podcast', group: 'Topics' },
  { label: 'Political', value: 'political', group: 'Topics' },
  { label: 'Product', value: 'product', group: 'Topics' },
  { label: 'Real estate', value: 'Real+Estate', group: 'Topics' },
  { label: 'Recession', value: 'Recession', group: 'Topics' },
  { label: 'SPAC', value: 'SPAC', group: 'Topics' },
  { label: 'Technical analysis', value: 'tanalysis', group: 'Topics' },
  { label: 'Warren Buffett', value: 'wbuffett', group: 'Topics' },
]

export const SECTORS: Option[] = [
  { label: 'All Sectors', value: 'all', group: 'Sectors' },
  { label: 'Basic Materials', value: 'Basic+Materials', group: 'Sectors' },
  { label: 'Conglomerates', value: 'Conglomerates', group: 'Sectors' },
  { label: 'Financial', value: 'Financial', group: 'Sectors' },
  { label: 'Healthcare', value: 'Healthcare', group: 'Sectors' },
  { label: 'Industrial Goods', value: 'Industrial+Goods', group: 'Sectors' },
  { label: 'Services', value: 'Services', group: 'Sectors' },
  { label: 'Technology', value: 'Technology', group: 'Sectors' },
  { label: 'Utilities', value: 'Utilities', group: 'Sectors' },
]

export const INDUSTRIES: Option[] = [
  { label: 'All Industries', value: 'all', group: 'Industry' },
  { label: 'Accident & Health Insurance', value: 'Accident+%26+Health+Insurance', group: 'Industry' },
  { label: 'Advertising Agencies', value: 'Advertising+Agencies', group: 'Industry' },
  {
    label: 'Aerospace/Defense - Major Diversified',
    value: 'Aerospace%2FDefense+%2D+Major+Diversified',
    group: 'Industry',
  },
  {
    label: 'Aerospace/Defense Products & Services',
    value: 'Aerospace%2FDefense+Products+%26+Services',
    group: 'Industry',
  },
  { label: 'Agricultural Chemicals', value: 'Agricultural+Chemicals', group: 'Industry' },
  { label: 'Air Delivery & Freight Services', value: 'Air+Delivery+%26+Freight+Services', group: 'Industry' },
  { label: 'Air Services, Other', value: 'Air+Services,+Other', group: 'Industry' },
  { label: 'Aluminum', value: 'Aluminum', group: 'Industry' },
  { label: 'Apparel Stores', value: 'Apparel+Stores', group: 'Industry' },
  { label: 'Appliances', value: 'Appliances', group: 'Industry' },
  { label: 'Application Software', value: 'Application+Software', group: 'Industry' },
  { label: 'Asset Management', value: 'Asset+Management', group: 'Industry' },
  { label: 'Auto Dealerships', value: 'Auto+Dealerships', group: 'Industry' },
  { label: 'Auto Manufacturers - Major', value: 'Auto+Manufacturers+%2D+Major', group: 'Industry' },
  { label: 'Auto Parts', value: 'Auto+Parts', group: 'Industry' },
  { label: 'Auto Parts Stores', value: 'Auto+Parts+Stores', group: 'Industry' },
  { label: 'Auto Parts Wholesale', value: 'Auto+Parts+Wholesale', group: 'Industry' },
  { label: 'Basic Materials Wholesale', value: 'Basic+Materials+Wholesale', group: 'Industry' },
  { label: 'Beverages - Brewers', value: 'Beverages+%2D+Brewers', group: 'Industry' },
  { label: 'Beverages - Soft Drinks', value: 'Beverages+%2D+Soft+Drinks', group: 'Industry' },
  { label: 'Beverages - Wineries & Distillers', value: 'Beverages+%2D+Wineries+%26+Distillers', group: 'Industry' },
  { label: 'Biotechnology', value: 'Biotechnology', group: 'Industry' },
  { label: 'Broadcasting - Radio', value: 'Broadcasting+%2D+Radio', group: 'Industry' },
  { label: 'Broadcasting - TV', value: 'Broadcasting+%2D+TV', group: 'Industry' },
  { label: 'Building Materials Wholesale', value: 'Building+Materials+Wholesale', group: 'Industry' },
  { label: 'Business Equipment', value: 'Business+Equipment', group: 'Industry' },
  { label: 'Business Services', value: 'Business+Services', group: 'Industry' },
  { label: 'Business Software & Services', value: 'Business+Software+%26+Services', group: 'Industry' },
  { label: 'Catalog & Mail Order Houses', value: 'Catalog+%26+Mail+Order+Houses', group: 'Industry' },
  { label: 'CATV Systems', value: 'CATV+Systems', group: 'Industry' },
  { label: 'Cement', value: 'Cement', group: 'Industry' },
  { label: 'Chemicals - Major Diversified', value: 'Chemicals+%2D+Major+Diversified', group: 'Industry' },
  { label: 'Cigarettes', value: 'Cigarettes', group: 'Industry' },
  { label: 'Cleaning Products', value: 'Cleaning+Products', group: 'Industry' },
  { label: 'Closed-End Fund - Debt', value: 'Closed%2DEnd+Fund+%2D+Debt', group: 'Industry' },
  { label: 'Closed-End Fund - Equity', value: 'Closed%2DEnd+Fund+%2D+Equity', group: 'Industry' },
  { label: 'Closed-End Fund - Foreign', value: 'Closed%2DEnd+Fund+%2D+Foreign', group: 'Industry' },
  { label: 'Communication Equipment', value: 'Communication+Equipment', group: 'Industry' },
  { label: 'Computer Based Systems', value: 'Computer+Based+Systems', group: 'Industry' },
  { label: 'Computer Peripherals', value: 'Computer+Peripherals', group: 'Industry' },
  { label: 'Computers Wholesale', value: 'Computers+Wholesale', group: 'Industry' },
  { label: 'Confectioners', value: 'Confectioners', group: 'Industry' },
  { label: 'Conglomerates', value: 'Conglomerates', group: 'Industry' },
  { label: 'Consumer Services', value: 'Consumer+Services', group: 'Industry' },
  { label: 'Copper', value: 'Copper', group: 'Industry' },
  { label: 'Credit Services', value: 'Credit+Services', group: 'Industry' },
  { label: 'Dairy Products', value: 'Dairy+Products', group: 'Industry' },
  { label: 'Data Storage Devices', value: 'Data+Storage+Devices', group: 'Industry' },
  { label: 'Department Stores', value: 'Department+Stores', group: 'Industry' },
  { label: 'Diagnostic Substances', value: 'Diagnostic+Substances', group: 'Industry' },
  { label: 'Discount, Variety Stores', value: 'Discount,+Variety+Stores', group: 'Industry' },
  { label: 'Diversified Communication Services', value: 'Diversified+Communication+Services', group: 'Industry' },
  { label: 'Diversified Computer Systems', value: 'Diversified+Computer+Systems', group: 'Industry' },
  { label: 'Diversified Electronics', value: 'Diversified+Electronics', group: 'Industry' },
  { label: 'Diversified Investments', value: 'Diversified+Investments', group: 'Industry' },
  { label: 'Diversified Machinery', value: 'Diversified+Machinery', group: 'Industry' },
  { label: 'Diversified Utilities', value: 'Diversified+Utilities', group: 'Industry' },
  { label: 'Drug Delivery', value: 'Drug+Delivery', group: 'Industry' },
  { label: 'Drug Manufacturers - Major', value: 'Drug+Manufacturers+%2D+Major', group: 'Industry' },
  { label: 'Drug Manufacturers - Other', value: 'Drug+Manufacturers+%2D+Other', group: 'Industry' },
  { label: 'Drug Related Products', value: 'Drug+Related+Products', group: 'Industry' },
  { label: 'Drug Stores', value: 'Drug+Stores', group: 'Industry' },
  { label: 'Drugs - Generic', value: 'Drugs+%2D+Generic', group: 'Industry' },
  { label: 'Drugs Wholesale', value: 'Drugs+Wholesale', group: 'Industry' },
  { label: 'Education & Training Services', value: 'Education+%26+Training+Services', group: 'Industry' },
  { label: 'Electric Utilities', value: 'Electric+Utilities', group: 'Industry' },
  { label: 'Electronic Equipment', value: 'Electronic+Equipment', group: 'Industry' },
  { label: 'Electronics Stores', value: 'Electronics+Stores', group: 'Industry' },
  { label: 'Electronics Wholesale', value: 'Electronics+Wholesale', group: 'Industry' },
  { label: 'Entertainment - Diversified', value: 'Entertainment+%2D+Diversified', group: 'Industry' },
  { label: 'Exchange Traded Fund', value: 'Exchange+Traded+Fund', group: 'Industry' },
  { label: 'Farm & Construction Machinery', value: 'Farm+%26+Construction+Machinery', group: 'Industry' },
  { label: 'Farm Products', value: 'Farm+Products', group: 'Industry' },
  { label: 'Food - Major Diversified', value: 'Food+%2D+Major+Diversified', group: 'Industry' },
  { label: 'Food Wholesale', value: 'Food+Wholesale', group: 'Industry' },
  { label: 'Foreign Money Center Banks', value: 'Foreign+Money+Center+Banks', group: 'Industry' },
  { label: 'Foreign Regional Banks', value: 'Foreign+Regional+Banks', group: 'Industry' },
  { label: 'Foreign Utilities', value: 'Foreign+Utilities', group: 'Industry' },
  { label: 'Gaming Activities', value: 'Gaming+Activities', group: 'Industry' },
  { label: 'Gas Utilities', value: 'Gas+Utilities', group: 'Industry' },
  { label: 'General Building Materials', value: 'General+Building+Materials', group: 'Industry' },
  { label: 'General Contractors', value: 'General+Contractors', group: 'Industry' },
  { label: 'General Entertainment', value: 'General+Entertainment', group: 'Industry' },
  { label: 'Gold', value: 'Gold', group: 'Industry' },
  { label: 'Grocery Stores', value: 'Grocery+Stores', group: 'Industry' },
  { label: 'Health Care Plans', value: 'Health+Care+Plans', group: 'Industry' },
  { label: 'Healthcare Information Services', value: 'Healthcare+Information+Services', group: 'Industry' },
  { label: 'Heavy Construction', value: 'Heavy+Construction', group: 'Industry' },
  { label: 'Home Furnishing Stores', value: 'Home+Furnishing+Stores', group: 'Industry' },
  { label: 'Home Furnishings & Fixtures', value: 'Home+Furnishings+%26+Fixtures', group: 'Industry' },
  { label: 'Home Health Care', value: 'Home+Health+Care', group: 'Industry' },
  { label: 'Home Improvement Stores', value: 'Home+Improvement+Stores', group: 'Industry' },
  { label: 'Hospitals', value: 'Hospitals', group: 'Industry' },
  { label: 'Housewares & Accessories', value: 'Housewares+%26+Accessories', group: 'Industry' },
  { label: 'Independent Oil & Gas', value: 'Independent+Oil+%26+Gas', group: 'Industry' },
  { label: 'Industrial Electrical Equipment', value: 'Industrial+Electrical+Equipment', group: 'Industry' },
  { label: 'Industrial Equipment & Components', value: 'Industrial+Equipment+%26+Components', group: 'Industry' },
  { label: 'Industrial Equipment Wholesale', value: 'Industrial+Equipment+Wholesale', group: 'Industry' },
  { label: 'Industrial Metals & Minerals', value: 'Industrial+Metals+%26+Minerals', group: 'Industry' },
  { label: 'Information & Delivery Services', value: 'Information+%26+Delivery+Services', group: 'Industry' },
  { label: 'Information Technology Services', value: 'Information+Technology+Services', group: 'Industry' },
  { label: 'Insider Trades', value: 'InsiderTrades', group: 'Industry' },
  { label: 'Insurance Brokers', value: 'Insurance+Brokers', group: 'Industry' },
  { label: 'Internet Information Providers', value: 'Internet+Information+Providers', group: 'Industry' },
  { label: 'Internet Service Providers', value: 'Internet+Service+Providers', group: 'Industry' },
  { label: 'Internet Software & Services', value: 'Internet+Software+%26+Services', group: 'Industry' },
  { label: 'Investment Brokerage - National', value: 'Investment+Brokerage+%2D+National', group: 'Industry' },
  { label: 'Investment Brokerage - Regional', value: 'Investment+Brokerage+%2D+Regional', group: 'Industry' },
  { label: 'Jewelry Stores', value: 'Jewelry+Stores', group: 'Industry' },
  { label: 'Life Insurance', value: 'Life+Insurance', group: 'Industry' },
  { label: 'Lodging', value: 'Lodging', group: 'Industry' },
  { label: 'Long Distance Carriers', value: 'Long+Distance+Carriers', group: 'Industry' },
  { label: 'Long-Term Care Facilities', value: 'Long%2DTerm+Care+Facilities', group: 'Industry' },
  { label: 'Lumber, Wood Production', value: 'Lumber,+Wood+Production', group: 'Industry' },
  { label: 'Machine Tools & Accessories', value: 'Machine+Tools+%26+Accessories', group: 'Industry' },
  { label: 'Major Airlines', value: 'Major+Airlines', group: 'Industry' },
  { label: 'Major Integrated Oil & Gas', value: 'Major+Integrated+Oil+%26+Gas', group: 'Industry' },
  { label: 'Management Services', value: 'Management+Services', group: 'Industry' },
  { label: 'Manufactured Housing', value: 'Manufactured+Housing', group: 'Industry' },
  { label: 'Marketing Services', value: 'Marketing+Services', group: 'Industry' },
  { label: 'Meat Products', value: 'Meat+Products', group: 'Industry' },
  { label: 'Medical Appliances & Equipment', value: 'Medical+Appliances+%26+Equipment', group: 'Industry' },
  { label: 'Medical Equipment Wholesale', value: 'Medical+Equipment+Wholesale', group: 'Industry' },
  { label: 'Medical Instruments & Supplies', value: 'Medical+Instruments+%26+Supplies', group: 'Industry' },
  { label: 'Medical Laboratories & Research', value: 'Medical+Laboratories+%26+Research', group: 'Industry' },
  { label: 'Metal Fabrication', value: 'Metal+Fabrication', group: 'Industry' },
  { label: 'Money Center Banks', value: 'Money+Center+Banks', group: 'Industry' },
  { label: 'Mortgage Investment', value: 'Mortgage+Investment', group: 'Industry' },
  { label: 'Movie Production, Theaters', value: 'Movie+Production,+Theaters', group: 'Industry' },
  { label: 'Multimedia & Graphics Software', value: 'Multimedia+%26+Graphics+Software', group: 'Industry' },
  { label: 'Music & Video Stores', value: 'Music+%26+Video+Stores', group: 'Industry' },
  { label: 'Networking & Communication Devices', value: 'Networking+%26+Communication+Devices', group: 'Industry' },
  { label: 'Nonmetallic Mineral Mining', value: 'Nonmetallic+Mineral+Mining', group: 'Industry' },
  { label: 'Office Supplies', value: 'Office+Supplies', group: 'Industry' },
  { label: 'Oil & Gas Drilling & Exploration', value: 'Oil+%26+Gas+Drilling+%26+Exploration', group: 'Industry' },
  { label: 'Oil & Gas Equipment & Services', value: 'Oil+%26+Gas+Equipment+%26+Services', group: 'Industry' },
  { label: 'Oil & Gas Pipelines', value: 'Oil+%26+Gas+Pipelines', group: 'Industry' },
  { label: 'Oil & Gas Refining & Marketing', value: 'Oil+%26+Gas+Refining+%26+Marketing', group: 'Industry' },
  { label: 'Packaging & Containers', value: 'Packaging+%26+Containers', group: 'Industry' },
  { label: 'Paper & Paper Products', value: 'Paper+%26+Paper+Products', group: 'Industry' },
  { label: 'Personal Computers', value: 'Personal+Computers', group: 'Industry' },
  { label: 'Personal Products', value: 'Personal+Products', group: 'Industry' },
  { label: 'Personal Services', value: 'Personal+Services', group: 'Industry' },
  { label: 'Photographic Equipment & Supplies', value: 'Photographic+Equipment+%26+Supplies', group: 'Industry' },
  { label: 'Pollution & Treatment Controls', value: 'Pollution+%26+Treatment+Controls', group: 'Industry' },
  { label: 'Printed Circuit Boards', value: 'Printed+Circuit+Boards', group: 'Industry' },
  { label: 'Processed & Packaged Goods', value: 'Processed+%26+Packaged+Goods', group: 'Industry' },
  { label: 'Processing Systems & Products', value: 'Processing+Systems+%26+Products', group: 'Industry' },
  { label: 'Property & Casualty Insurance', value: 'Property+%26+Casualty+Insurance', group: 'Industry' },
  { label: 'Property Management', value: 'Property+Management', group: 'Industry' },
  { label: 'Publishing - Books', value: 'Publishing+%2D+Books', group: 'Industry' },
  { label: 'Publishing - Newspapers', value: 'Publishing+%2D+Newspapers', group: 'Industry' },
  { label: 'Publishing - Periodicals', value: 'Publishing+%2D+Periodicals', group: 'Industry' },
  { label: 'Railroads', value: 'Railroads', group: 'Industry' },
  { label: 'Real Estate Development', value: 'Real+Estate+Development', group: 'Industry' },
  { label: 'Recreational Goods, Other', value: 'Recreational+Goods,+Other', group: 'Industry' },
  { label: 'Recreational Vehicles', value: 'Recreational+Vehicles', group: 'Industry' },
  { label: 'Regional - Mid-Atlantic Banks', value: 'Regional+%2D+Mid%2DAtlantic+Banks', group: 'Industry' },
  { label: 'Regional - Midwest Banks', value: 'Regional+%2D+Midwest+Banks', group: 'Industry' },
  { label: 'Regional - Northeast Banks', value: 'Regional+%2D+Northeast+Banks', group: 'Industry' },
  { label: 'Regional - Pacific Banks', value: 'Regional+%2D+Pacific+Banks', group: 'Industry' },
  { label: 'Regional - Southeast Banks', value: 'Regional+%2D+Southeast+Banks', group: 'Industry' },
  { label: 'Regional - Southwest Banks', value: 'Regional+%2D+Southwest+Banks', group: 'Industry' },
  { label: 'Regional Airlines', value: 'Regional+Airlines', group: 'Industry' },
  { label: 'REIT - Diversified', value: 'REIT+%2D+Diversified', group: 'Industry' },
  { label: 'REIT - Healthcare Facilities', value: 'REIT+%2D+Healthcare+Facilities', group: 'Industry' },
  { label: 'REIT - Hotel/Motel', value: 'REIT+%2D+Hotel%2FMotel', group: 'Industry' },
  { label: 'REIT - Industrial', value: 'REIT+%2D+Industrial', group: 'Industry' },
  { label: 'REIT - Office', value: 'REIT+%2D+Office', group: 'Industry' },
  { label: 'REIT - Residential', value: 'REIT+%2D+Residential', group: 'Industry' },
  { label: 'REIT - Retail', value: 'REIT+%2D+Retail', group: 'Industry' },
  { label: 'Rental & Leasing Services', value: 'Rental+%26+Leasing+Services', group: 'Industry' },
  { label: 'Research Services', value: 'Research+Services', group: 'Industry' },
  { label: 'Residential Construction', value: 'Residential+Construction', group: 'Industry' },
  { label: 'Resorts & Casinos', value: 'Resorts+%26+Casinos', group: 'Industry' },
  { label: 'Restaurants', value: 'Restaurants', group: 'Industry' },
  { label: 'Rubber & Plastics', value: 'Rubber+%26+Plastics', group: 'Industry' },
  { label: 'Savings & Loans', value: 'Savings+%26+Loans', group: 'Industry' },
  { label: 'Scientific & Technical Instruments', value: 'Scientific+%26+Technical+Instruments', group: 'Industry' },
  { label: 'Security & Protection Services', value: 'Security+%26+Protection+Services', group: 'Industry' },
  { label: 'Security Software & Services', value: 'Security+Software+%26+Services', group: 'Industry' },
  { label: 'Semiconductor - Broad Line', value: 'Semiconductor+%2D+Broad+Line', group: 'Industry' },
  { label: 'Semiconductor - Integrated Circuits', value: 'Semiconductor+%2D+Integrated+Circuits', group: 'Industry' },
  { label: 'Semiconductor - Specialized', value: 'Semiconductor+%2D+Specialized', group: 'Industry' },
  { label: 'Semiconductor Equipment & Materials', value: 'Semiconductor+Equipment+%26+Materials', group: 'Industry' },
  { label: 'Semiconductor- Memory Chips', value: 'Semiconductor%2D+Memory+Chips', group: 'Industry' },
  { label: 'Shipping', value: 'Shipping', group: 'Industry' },
  { label: 'Silver', value: 'Silver', group: 'Industry' },
  { label: 'Small Tools & Accessories', value: 'Small+Tools+%26+Accessories', group: 'Industry' },
  { label: 'Specialized Health Services', value: 'Specialized+Health+Services', group: 'Industry' },
  { label: 'Specialty Chemicals', value: 'Specialty+Chemicals', group: 'Industry' },
  { label: 'Specialty Eateries', value: 'Specialty+Eateries', group: 'Industry' },
  { label: 'Specialty Retail, Other', value: 'Specialty+Retail,+Other', group: 'Industry' },
  { label: 'Sporting Activities', value: 'Sporting+Activities', group: 'Industry' },
  { label: 'Sporting Goods', value: 'Sporting+Goods', group: 'Industry' },
  { label: 'Sporting Goods Stores', value: 'Sporting+Goods+Stores', group: 'Industry' },
  { label: 'Staffing & Outsourcing Services', value: 'Staffing+%26+Outsourcing+Services', group: 'Industry' },
  { label: 'Steel & Iron', value: 'Steel+%26+Iron', group: 'Industry' },
  { label: 'Surety & Title Insurance', value: 'Surety+%26+Title+Insurance', group: 'Industry' },
  { label: 'Synthetics', value: 'Synthetics', group: 'Industry' },
  { label: 'Technical & System Software', value: 'Technical+%26+System+Software', group: 'Industry' },
  { label: 'Technical Services', value: 'Technical+Services', group: 'Industry' },
  { label: 'Telecom Services - Domestic', value: 'Telecom+Services+%2D+Domestic', group: 'Industry' },
  { label: 'Telecom Services - Foreign', value: 'Telecom+Services+%2D+Foreign', group: 'Industry' },
  { label: 'Textile - Apparel Clothing', value: 'Textile+%2D+Apparel+Clothing', group: 'Industry' },
  {
    label: 'Textile - Apparel Footwear & Accessories',
    value: 'Textile+%2D+Apparel+Footwear+%26+Accessories',
    group: 'Industry',
  },
  { label: 'Textile Industrial', value: 'Textile+Industrial', group: 'Industry' },
  { label: 'Tobacco Products, Other', value: 'Tobacco+Products,+Other', group: 'Industry' },
  { label: 'Toy & Hobby Stores', value: 'Toy+%26+Hobby+Stores', group: 'Industry' },
  { label: 'Toys & Games', value: 'Toys+%26+Games', group: 'Industry' },
  { label: 'Trucking', value: 'Trucking', group: 'Industry' },
  { label: 'Trucks & Other Vehicles', value: 'Trucks+%26+Other+Vehicles', group: 'Industry' },
  { label: 'Waste Management', value: 'Waste+Management', group: 'Industry' },
  { label: 'Water Utilities', value: 'Water+Utilities', group: 'Industry' },
  { label: 'Wireless Communications', value: 'Wireless+Communications', group: 'Industry' },
]

export const COUNTRIES: Option[] = [
  { label: 'All Countries', value: 'all', group: 'Country' },
  { label: 'Argentina', value: 'Argentina', group: 'Country' },
  { label: 'Australia', value: 'Australia', group: 'Country' },
  { label: 'Austria', value: 'Austria', group: 'Country' },
  { label: 'Bahamas', value: 'Bahamas', group: 'Country' },
  { label: 'Belgium', value: 'Belgium', group: 'Country' },
  { label: 'Bermuda', value: 'Bermuda', group: 'Country' },
  { label: 'British Virgin Islands', value: 'British+Virgin+Islands', group: 'Country' },
  { label: 'Cambodia', value: 'Cambodia', group: 'Country' },
  { label: 'Canada', value: 'Canada', group: 'Country' },
  { label: 'Cayman Islands', value: 'Cayman+Islands', group: 'Country' },
  { label: 'Channel Islands', value: 'Channel+Islands', group: 'Country' },
  { label: 'Chile', value: 'Chile', group: 'Country' },
  { label: 'China', value: 'China', group: 'Country' },
  { label: 'Colombia', value: 'Colombia', group: 'Country' },
  { label: 'Cyprus', value: 'Cyprus', group: 'Country' },
  { label: 'Denmark', value: 'Denmark', group: 'Country' },
  { label: 'Egypt', value: 'Egypt', group: 'Country' },
  { label: 'Finland', value: 'Finland', group: 'Country' },
  { label: 'France', value: 'France', group: 'Country' },
  { label: 'Germany', value: 'Germany', group: 'Country' },
  { label: 'Greece', value: 'Greece', group: 'Country' },
  { label: 'Hong Kong', value: 'Hong+Kong', group: 'Country' },
  { label: 'India', value: 'India', group: 'Country' },
  { label: 'Indonesia', value: 'Indonesia', group: 'Country' },
  { label: 'Ireland', value: 'Ireland', group: 'Country' },
  { label: 'Israel', value: 'Israel', group: 'Country' },
  { label: 'Italy', value: 'Italy', group: 'Country' },
  { label: 'Japan', value: 'Japan', group: 'Country' },
  { label: 'Luxembourg', value: 'Luxembourg', group: 'Country' },
  { label: 'Malaysia', value: 'Malaysia', group: 'Country' },
  { label: 'Marshall Islands', value: 'Marshall+Islands', group: 'Country' },
  { label: 'Mexico', value: 'Mexico', group: 'Country' },
  { label: 'Monaco', value: 'Monaco', group: 'Country' },
  { label: 'Netherlands', value: 'Netherlands', group: 'Country' },
  { label: 'Netherlands Antilles', value: 'Netherlands+Antilles', group: 'Country' },
  { label: 'Norway', value: 'Norway', group: 'Country' },
  { label: 'Panama', value: 'Panama', group: 'Country' },
  { label: 'Peru', value: 'Peru', group: 'Country' },
  { label: 'Philippines', value: 'Philippines', group: 'Country' },
  { label: 'Poland', value: 'Poland', group: 'Country' },
  { label: 'Portugal', value: 'Portugal', group: 'Country' },
  { label: 'Russia', value: 'Russia', group: 'Country' },
  { label: 'Singapore', value: 'Singapore', group: 'Country' },
  { label: 'South Africa', value: 'South+Africa', group: 'Country' },
  { label: 'South Korea', value: 'South+Korea', group: 'Country' },
  { label: 'Spain', value: 'Spain', group: 'Country' },
  { label: 'Sweden', value: 'Sweden', group: 'Country' },
  { label: 'Switzerland', value: 'Switzerland', group: 'Country' },
  { label: 'Taiwan', value: 'Taiwan', group: 'Country' },
  { label: 'Thailand', value: 'Thailand', group: 'Country' },
  { label: 'Turkey', value: 'Turkey', group: 'Country' },
  { label: 'United Arab Emirates', value: 'United+Arab+Emirates', group: 'Country' },
  { label: 'United Kingdom', value: 'United+Kingdom', group: 'Country' },
  { label: 'United States', value: 'United+States', group: 'Country' },
]

export const COLLECTIONS: Option[] = [
  { label: 'All Collections', value: 'all', group: 'Collections' },
  { label: 'US Major Airlines', value: 'Airlines', group: 'Collections' },
  { label: 'Big US Tech Companies', value: 'BigTechUS', group: 'Collections' },
  { label: 'Blockchain', value: 'Blockchain', group: 'Collections' },
  { label: 'Cannabis Stocks', value: 'Cannabis-stocks', group: 'Collections' },
  { label: 'China Big Tech Companies', value: 'ChinaTech', group: 'Collections' },
  { label: 'Copper ETFs', value: 'Copper-ETFs', group: 'Collections' },
  { label: 'Clean Energy Companies', value: 'CleanEnergy', group: 'Collections' },
  { label: 'Cloud Computing', value: 'CloudComputing', group: 'Collections' },
  { label: 'Major Cruise Lines', value: 'CruiseLines', group: 'Collections' },
  { label: 'Digital Payments', value: 'DigitalPayments', group: 'Collections' },
  { label: 'Electric Vehicles Companies', value: 'EV', group: 'Collections' },
  { label: 'FAANG', value: 'FAANG', group: 'Collections' },
  { label: 'Gambling Companies', value: 'Gambling', group: 'Collections' },
  { label: 'Gaming', value: 'Gaming', group: 'Collections' },
  { label: 'Gold ETFs', value: 'Gold-ETFs', group: 'Collections' },
  { label: 'Immunology & Biotech', value: 'Immunology', group: 'Collections' },
  { label: 'Jim Simons', value: 'JimSimons', group: 'Collections' },
  { label: 'Large Hotel Brands', value: 'Hotels', group: 'Collections' },
  { label: 'Lumber ETFs', value: 'Lumber-ETFs', group: 'Collections' },
  { label: 'Meme Stocks', value: 'Meme', group: 'Collections' },
  { label: 'Oil ETFs', value: 'Oil-ETFs', group: 'Collections' },
  { label: 'Real Estate ETFs', value: 'REIT-ETFs', group: 'Collections' },
  { label: 'Robotics and Artificial Intelligence', value: 'Robotics-AI', group: 'Collections' },
  { label: 'Sea Decarbonization', value: 'SeaDecarbonization', group: 'Collections' },
  { label: 'Semiconductor Companies', value: 'Semiconductor', group: 'Collections' },
  { label: 'Silver ETFs', value: 'Silver-ETFs', group: 'Collections' },
  { label: 'S&P 500 ETFs', value: 'SP500ETF', group: 'Collections' },
  { label: 'Streaming companies', value: 'Streaming', group: 'Collections' },
  { label: 'Top Phamaceutical Companies', value: 'TopPharma', group: 'Collections' },
  { label: 'Large US Auto Manufacturers', value: 'US-Auto-Large', group: 'Collections' },
  { label: 'Large US Banks', value: 'USBanks', group: 'Collections' },
  { label: 'Warren Buffet Stocks', value: 'WarrenBuffet', group: 'Collections' },
]
