/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticationImport } from './routes/authentication'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthIndexImport } from './routes/_auth.index'
import { Route as AuthSavedImport } from './routes/_auth.saved'
import { Route as AuthDetailsSymbolImport } from './routes/_auth.details.$symbol'

// Create/Update Routes

const AuthenticationRoute = AuthenticationImport.update({
  path: '/authentication',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSavedRoute = AuthSavedImport.update({
  path: '/saved',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDetailsSymbolRoute = AuthDetailsSymbolImport.update({
  path: '/details/$symbol',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/authentication': {
      preLoaderRoute: typeof AuthenticationImport
      parentRoute: typeof rootRoute
    }
    '/_auth/saved': {
      preLoaderRoute: typeof AuthSavedImport
      parentRoute: typeof AuthImport
    }
    '/_auth/': {
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/details/$symbol': {
      preLoaderRoute: typeof AuthDetailsSymbolImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthRoute.addChildren([
    AuthSavedRoute,
    AuthIndexRoute,
    AuthDetailsSymbolRoute,
  ]),
  AuthenticationRoute,
])

/* prettier-ignore-end */
